name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v3

    - name: Installer Java (requis pour Android)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Installer Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Installer les dépendances
      run: flutter pub get

    - name: Compiler l'APK en mode Release
      run: flutter build apk --release

    - name: Sauvegarder l'APK généré
      uses: actions/upload-artifact@v4
      with:
        name: application-apk
        path: build/app/outputs/flutter-apk/app-release.apk
